### ISSUE TITLE
Too many parties disconnects client from server

### ISSUE THREAD

**Issue by hotdog95** [vincentmet/CustomQuests#28]
If clients all create a party each (5 players with 110 quests each) the client will no longer be able to join the server after quitting

I removed the questing parties file before starting the server back up, and it fixes this issue

I know there is a rewrite in progress, but I thought I would report this bug just in case it helps with the rewrite to fine tune the new version. Looking forward to the new features and improaved functionality!

Issue is caused by: MessageUpdateQuestPartiesServerToClient
![Annotation 2020-07-27 135512](https://user-images.githubusercontent.com/19279025/88502275-4a6e8580-d011-11ea-8164-b9e837be2787.png)

**Comment by vincentmetevelis** [comment]
The thing is, i started working on parties, but never finished integrating it with the rest of the mod before starting work on the rewrite. Therefor i did not optimize stuff for parties.
Command is "/customquests party deleteall" to remove all parties (which would be gone anyway on server restart IIRC). If that doesnt work, delete the file "QuestingParties.json" in the world folder (after turning server off).
Closing this issue, since i'm not fixing this in the old version anymore.
